#Locators Creer un Dossier
MesFichier = "//a[@title='Mes fichiers']"
NomPage = "//button[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-fileUpload-button-button']"
Creer = "//button[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createContent-button-button']"
PageCreer = "//li[@id='yui-gen5']//a[@class='yuimenuitemlabel yuimenuitemlabel-hassubmenu']//span[1]"
CreerDossier = "//span[@class='folder-file']"
PageCreerDossier = "//h2[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder-dialogHeader']"
lnk_ChampNom = "//input[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder_prop_cm_name']"
lnk_ChampTitre = "//input[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder_prop_cm_title']"
Enregistrer = "//button[@id='template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder-form-submit-button']"
lnk_ChampDescripton = "//textarea[@title='Description du contenu']"

#locators Supprimer Un Dossier
lnk_CheckBoxFin = "')]/ancestor::tr/descendant::input[@name='fileChecked']"
btn_Supprimer = "//span[normalize-space()='Supprimer']"
btn_ElementsSelectionnes = "template_x002e_documentlist_v2_x002e_myfiles_x0023_default-selectedItems-button-button"
btn_SurpprimerDossierConfirmer = "//button[normalize-space()='Supprimer']"
lnk_CheckBoxDeb = "//a[contains(text(),'"
#locators Copier Un Dossier
lnk_ElemSel = "//button[contains(text(),'Eléments sélectionnés... ▾')]"
lnk_CopyTo = "//span[@class='onActionCopyTo']"
btn_TousSite = "xpath=//button[text()='Tous les sites']"
lnk_SitDeb = "//h4[text()='"
lnk_SitFin = "']"
lnk_Documents = "//span[text()='Documents']"
btn_Copier = "//button[normalize-space()='Copier']"
lnk_EspDoc = "//a[@title='Espace documentaire']"
lnk_CopyConfDeb = "//a[@href='#' and text()='"
lnk_CopyConfFin = "']"
#locators Ajouter un commentaire
lnk_ComDebut = "//a[contains(text(),'"
lnk_ComFin = "')]/ancestor::tr/descendant::a[@title='Commenter sur ce dossier']"
lbl_AjCom = "//h2[text()='Ajouter votre commentaire...']"
btn_AjCom = "//div[@class='buttons']//button[text()='Ajouter un commentaire']"
frm_AjCom = "//iframe[@id='template_x002e_comments_x002e_folder-details_x0023_default-add-content_ifr']"
txt_AjCom = "id=tinymce"
lbl_Com = "//h2[text()='Commentaires']"
lnk_VerComDebut = "//div[@class='comments-list']//p[text()='"
lnk_VerComFin = "']"

